### ISSUE TITLE
Confused by error response from Goggle. Did the spec on [dimension] filters change?

### ISSUE THREAD

**Issue by Ben-Fenner** [dailytics/google_analytics_v4_api#3]
We're evaluating which GAv4 gem we want to go with and this one seems the most promising. However things have changed a bit and it seems Google is no longer using the `dimensionFilter` key to accept filters.

I envision this class (and the README docs) needs a little updating: https://github.com/dailytics/google_analytics_v4_api/blob/main/lib/google_analytics_v4_api/report.rb

Would a pull request or two from me be welcome to update this gem? Is anyone still here @luctus? Just checking before I potentially hard-fork on Monday to make this code work for us.

**Comment by luctus** [comment]
Hey @Ben-Fenner!

Thanks for reporting this issue. 

I will try to take a look during the weekend. If can't make it, I'd love your help here.

Cheers.

**Comment by luctus** [comment]
BTW, can you elaborate your point? I just revisit their documentation and everything looks the same:

https://developers.google.com/analytics/devguides/reporting/data/v1/basics#group_and_filter_data

**Comment by Ben-Fenner** [comment]
Thank you for the reply @luctus!

I just came back to say I'm confused, since their docs say things should work. Here's a slightly more relevant link?
https://developers.google.com/analytics/devguides/reporting/data/v1/basics#filter

So we've come to the same conclusion. Anyway, I'll come back with concrete error messages for you and a way to reproduce the issue. But even if I do, I wonder if maybe I'm using the filters wrong anyway, and fixing that on my side will solve the problem.

Sit tight. I'll report back.

**Comment by Ben-Fenner** [comment]
So here is what I'm doing, and what I'm seeing as a response.

In a Rails console:
```RUBY
scope    = 'https://www.googleapis.com/auth/analytics.readonly'
token    = GoogleAnalytics.service_account_access_token(scope).token # Our custom app code. Confirmed valid token.
client   = GoogleAnalyticsV4Api::Client.new(token)
account  = client.account('accounts/xxxxxxx')       #  Account display name: [Redacted]
property = account.property('properties/xxxxxxxxx') # Property display name: [Redacted]

# Yes, these filters are completely malformed. This is how we did it in GA3, so just throwing it against the wall for now.
filters    = ["pagePath=~/manual_transmissions/.+/show_public",
              "hostName!~subdomain.example.com"]
begin_date = Date.parse('2023-06-01')
end_date   = Date.parse('2023-08-01')

report = GoogleAnalyticsV4Api::Report.new(
  start_date:       begin_date,
  end_date:         end_date,
  dimensions:       ['pagePath', 'hostName', 'date'],
  dimension_filter: filters,
  metrics:          ['screenPageViews'],
  limit:            10_000)


response = property.run_report(report)
```
And here is the value of `response` returned:
```
#<GoogleAnalyticsV4Api::ReportResponse:0x00005620f6f92ca8
@body={
  "error"=>{
    "code"=>400,
    "message"=>"Invalid JSON payload received. Unknown name \"dimensionFilter\": Proto field is not repeating, cannot start list.",
    "status"=>"INVALID_ARGUMENT",
    "details"=>[{
      "@type"=>"type.googleapis.com/google.rpc.BadRequest",
               "fieldViolations"=>[{
                 "description"=>"Invalid JSON payload received. Unknown name \"dimensionFilter\": Proto field is not repeating, cannot start list."
               }]
    }]
  }
},
@raw_dimension_headers=[],
@raw_metric_headers=[],
@rows=[],
@row_cont=0,
@metadata=nil,
@kind=nil>
```

Everything works swimmingly if I instead do this:
```RUBY
report = GoogleAnalyticsV4Api::Report.new(
  start_date:       begin_date,
  end_date:         end_date,
  dimensions:       ['pagePath', 'hostName', 'date'],
  dimension_filter: {},
  metrics:          ['screenPageViews'],
  limit:            GoogleAnalytics::MAX_RESULTS)
```

Which I assume forgoes the `dimensionFilter` key from the request.


So yah, I'm still not convinced that there is an issue with the gem. It might be that my malformed filters just need work. I will work on converting those from GA3 style to GA4 and see how that goes. In the mean time I'll take any insight you have. :+1:

**Comment by luctus** [comment]
There are many users at Dailytics running reports with filters, so I'd say it's working fine. The error message is very vague to be fair.

Could you please try with this filter var?
```rb
filter = {
  "andGroup": {
    "expressions": [
      {
        "filter": {
          "fieldName": "pagePath",
          "stringFilter": {
            "matchType": "FULL_REGEXP",
            "value": "/manual_transmissions/.+/show_public",
            "caseSensitive": false
          }
        }
      },
      {
        "filter": {
          "fieldName": "hostName",
          "stringFilter": {
            "matchType": "CONTAINS",
            "value": "subdomain.example.com",
            "caseSensitive": false
          }
        }
      }
    ]
  }
}
```

**Comment by Ben-Fenner** [comment]
Thank you @luctus. You're right, the error message from Google is the source of my confusion. I didn't intend for you to do my homework for me, but your filter example has me on the right track now and I see that this ticket probably never needed to exist.

Feel free to close the ticket. I've got results coming back while using filters now and I'm quite happy. :D

**Comment by luctus** [comment]
No worries, @Ben-Fenner!

It took me a while to finally understand the structure of those filters and I am always happy to help where I can.

Let me know if you have any issues at all with this API.

**Comment by Ben-Fenner** [comment]
If anyone from the future gets here and wants to know where I ended up, here are the actual filters that got my job done.  
Make note of the `notExpression` for negation.
```RUBY
GA4_FILTER_PUBLIC = {
    'filter': {
      'fieldName': 'pagePath',
      'stringFilter': {
        'matchType':     'FULL_REGEXP',
        'value':         '^' + '/manual_transmissions/' + '.+' + '/show_public' + '$',
        'caseSensitive': false
      }
    }
  }.freeze

GA4_FILTER_EXCLUDE_SUBDOMAIN = {
    'notExpression': {
      'filter': {
        'fieldName': 'hostName',
        'stringFilter': {
          'matchType':     'CONTAINS',
          'value':         'subdomain.example.com',
          'caseSensitive': false
        }
      }
    }
  }.freeze

filters = { 'andGroup': { 'expressions': [GA4_FILTER_PUBLIC, GA4_FILTER_EXCLUDE_SUBDOMAIN] } }
```
